// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATC2HO5R-d5KPWRH69kHgD9HppbivpliU',
    appId: '1:682842105678:web:7b11a790d239bf1d75e01f',
    messagingSenderId: '682842105678',
    projectId: 'basemap-88186',
    authDomain: 'basemap-88186.firebaseapp.com',
    storageBucket: 'basemap-88186.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvqHrvoa2i5AiE9eAlNzJWmuk4FAfni7w',
    appId: '1:682842105678:android:934e87fb7a40c25b75e01f',
    messagingSenderId: '682842105678',
    projectId: 'basemap-88186',
    storageBucket: 'basemap-88186.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyR61pVSXgv5JeV2X8W3XKBH-6zvbSDeE',
    appId: '1:682842105678:ios:42e72390783acef075e01f',
    messagingSenderId: '682842105678',
    projectId: 'basemap-88186',
    storageBucket: 'basemap-88186.appspot.com',
    iosBundleId: 'com.example.basemap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyR61pVSXgv5JeV2X8W3XKBH-6zvbSDeE',
    appId: '1:682842105678:ios:42e72390783acef075e01f',
    messagingSenderId: '682842105678',
    projectId: 'basemap-88186',
    storageBucket: 'basemap-88186.appspot.com',
    iosBundleId: 'com.example.basemap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATC2HO5R-d5KPWRH69kHgD9HppbivpliU',
    appId: '1:682842105678:web:a643b1de95672b4075e01f',
    messagingSenderId: '682842105678',
    projectId: 'basemap-88186',
    authDomain: 'basemap-88186.firebaseapp.com',
    storageBucket: 'basemap-88186.appspot.com',
  );

}